### ISSUE TITLE
Title 未更新

### ISSUE THREAD

**Issue by Korver2017** [Protype/Wrinkle#1]
開發過程好像有修改名稱， `Wrinkled -> Wrinkle` ，下圖所示 `title` 的部分似乎沒有改到

這是一個很棒的專案，期待您的擴充與力作 🤣 （假裝路人？

![image](https://user-images.githubusercontent.com/25289960/66360579-3e480780-e9ae-11e9-9b38-4dd54cfeb709.png)

![image](https://user-images.githubusercontent.com/25289960/66360671-85ce9380-e9ae-11e9-9a48-f7d7fcfbf25f.png)

**Comment by wake** [comment]
謝啦
